[package]
name = "dioxusProject"
version = "0.1.0"
edition = "2021"

[application]
out_dir = "dist" #Build directiory

[dependencies]
dioxus = "0.4.3"
dioxus-fullstack = "0.4.3"

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]